global:
  language: en
  weather: weather.domov
  outside_temperature: sensor.multi_sensor_3
  outside_humidity: sensor.multi_sensor
  # alarm: alarm_control_panel.alarm_system
  inside_temperature: sensor.living_room_temperature