substitutions:
  plug_name: akarium_switch

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
       