# 2 gang wall switch
# https://www.aliexpress.com/item/4000191335997.html?spm=a2g0s.9042311.0.0.2e254c4dTgpups
# https://templates.blakadder.com/girier_JRSWR-SEU01-2.html (tasmota)

substitutions:
  switch_name: sts_01

esphome:
  name: ${switch_name}
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 24h
  
ota:

web_server:
  port: 80

status_led:
  pin: GPIO16
  
output:
  - platform: gpio
    pin: 4
    id: relay1
  - platform: gpio
    pin: 13
    id: relay2

light:
  - platform: binary
    name: "${switch_name}_relay_1"
    id: "${switch_name}_relay_1"
    output: relay1
    restore_mode: ALWAYS_OFF
  - platform: binary
    name: "${switch_name}_relay_2"
    id: "${switch_name}_relay_2"
    output: relay2
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin: 14
    filters:
      - invert:
      - delayed_on: 20ms
    name: "${switch_name}_button_1"
    id: "${switch_name}_button_1"
    internal: true
    on_release:
      then:
        - light.toggle: "${switch_name}_relay_1"
  - platform: gpio
    pin: 12
    filters:
      - invert:
      - delayed_on: 20ms
    name: "${switch_name}_button_2"
    id: "${switch_name}_button_2"
    internal: true
    on_release:
      then:
        - light.toggle: "${switch_name}_relay_2"